export const environment = {
  
  urlAddress:'http://localhost:50653',
  urlAddress4200:'http://localhost:4200/#/',
  Domain:'http://localhost:50653/',
  project: 'http://localhost:50653/api/project',
  GetProjectForRequest:'http://localhost:50653/api/project/GetProjectForRequest',
  DeleteProject:'http://localhost:50653/api/project/SoftDelete/',
  stackeholders: 'http://localhost:50653/api/Stackeholders/',
  GetAllStackholdersByProjectID: 'http://localhost:50653/api/Stackeholders/GetStackeholdersByProjectId/',
  postListOfStackholders: 'http://localhost:50653/api/Stackeholders/',
  postListOfMilestoness: 'http://localhost:50653/api/MileStones/',
  getMileStoneById:'http://localhost:50653/api/MileStones/',
  updateMileStoneByid:'http://localhost:50653/api/MileStones/updateMileStoneById/',
  ProjectTeams: 'http://localhost:50653/api/ProjectTeam/',
  canreqbyprojectID:'http://localhost:50653/api/project/canreqbyprojeID/',
  GetProjectTeamsByProjectPositionId: 'http://localhost:50653/api/ProjectTeam/GetProjectTeamsByProjectPositionId/',
  organizations: 'http://localhost:50653/api/Organizations/',
  clients: 'http://localhost:50653/api/Clients/',
  employees: 'http://localhost:50653/api/Employees/',
  requests: 'http://localhost:50653/api/Request/',
  requestStatus: 'http://localhost:50653/api/RequestStatus/',
  requestTypes: 'http://localhost:50653/api/RequestTypes/',
  requestPeriorities: 'http://localhost:50653/api/RequestPeriorities/',
  department: 'http://localhost:50653/api/Departments/',
  requestSubCategory: 'http://localhost:50653/api/RequestSubCategory/',
  requestSubCategoryById:'http://localhost:50653/api/RequestSubCategory/',
  filterSubCategoriesByCategoryId:'http://localhost:50653/api/RequestSubCategory/GetRequestSubCategoryDTOByCatId/',
  editrequestSubCategory:'http://localhost:50653/api/RequestSubCategory/',
  requestCategory: 'http://localhost:50653/api/RequestCategory/',
  getCategory:'http://localhost:50653/api/RequestCategory/',
  updateCategory:'http://localhost:50653/api/RequestCategory/',
  projectPositions: 'http://localhost:50653/api/ProjectPositions/',
  getDepartmentByEmpID: 'http://localhost:50653/api/Departments/GetDepartmentByEmployeeId/',
  projectTypes: 'http://localhost:50653/api/ProjectTypes/',
  asset: 'http://localhost:50653/api/Assets/',
  GetAllRequestByClientId: 'http://localhost:50653/api/Request/GetAllRequestByClientId/',
  reqMode: 'http://localhost:50653/api/RequestModes/',
  GetAllMilestonsByProjectId: 'http://localhost:50653/api/MileStones/GetMileStonesByProjectId/',
  GetAllTeamsByProjectId: 'http://localhost:50653/api/ProjectTeam/GetProjectTeamsByProjectId/',
  GetAllDocumentByProjectId: 'http://localhost:50653/api/ProjectDocument/GetProjectDocumentsByProjectId/',
  User: 'http://localhost:50653/api',
  postProjectDocumentByProjectID: 'http://localhost:50653/api/ProjectDocument/SaveDocument',
  uploadFile: 'http://localhost:50653/api/ProjectDocument/uploadfile/',
  deletestakeholder: 'http://localhost:50653/api/Stackeholders/',
  updatestackholder:'http://localhost:50653/api/Stackeholders/updatestakehodersbyID/',

  getStackholderbyId:'http://localhost:50653/api/Stackeholders/',
  deletemilestone: ' http://localhost:50653/api/MileStones/',
  deleteteam: 'http://localhost:50653/api/ProjectTeam/',
  GetClientByProjectId: 'http://localhost:50653/api/project/GetClientByProjectId/',

  deletedocument: 'http://localhost:50653/api/ProjectDocument/',
  updatestakeholdersbyprojectid: 'http://localhost:50653/api/Stackeholders/updatestakehodersByProjectId/1',
  updateteamsbyprojectid: 'http://localhost:50653/api/ProjectTeam/updateteamsByProjectId/1',
  updatemilestonebyprojectid: 'http://localhost:50653/api/MileStones/PutmilestonesDTOByProjectId/1',
  updatedocumectsbyprojectid: 'http://localhost:50653/api/ProjectDocument/PutDocumentsDTOByProjectId/',
  updateProject: 'http://localhost:50653/api/Project/',
  GetProjectById: 'http://localhost:50653/api/Project/',
  uploadImage: 'http://localhost:50653/api/UploadImage/uploadimage/',
  addRequstImages: 'http://localhost:50653/api/RequestImages',
  RequestDescription: 'http://localhost:50653/api/RequestDescription',
  assignedRequests: 'http://localhost:50653/api/AssignedRequests',
  getTeambyId:'http://localhost:50653/api/Teams/',
  addteams:'http://localhost:50653/api/Teams/',
  GetEmployeessByTeamId:'http://localhost:50653/api/ProjectTeam/GetEmployeessByTeamId/',
  GetRequestImageByRequestId:'http://localhost:50653/api/RequestImages/GetRequestImageByRequestId/',
  GetAllRequestByEmployeeId:'http://localhost:50653/api/AssignedRequests/GetAllRequestByEmployeeId/',
  GetAllProjectTeamsByProjectID:'http://localhost:50653/api/ProjectTeam/GetProjectTeamsByProjectId/',
  GetAllProjectTeamIdByProjectIDandTeamIdAndPoaitionId:'http://localhost:50653/api/ProjectTeam/GetProjectTeamByProjectIdAndTeamIdAndProjectPositionId/',
  GetProjectTeamByProjectPositionIdAndEmployeeId:'http://localhost:50653/api/ProjectTeam/GetProjectTeamByProjectPositionIdAndEmployeeId/',
  GetAllRequestByProjectTeamId:'http://localhost:50653/api/Request/GetAllRequestByProjectTeamId/',
  GetAllProjectsByEmployeeId:'http://localhost:50653/api/project/GetAllProjectsByEmployeeId/',
  GetClientsByEmployeeId:'http://localhost:50653/api/project/GetClientsByEmployeeId/',
  GetAllProjectTeamsByProjectIds:'http://localhost:50653/api/ProjectTeam/GetAllProjectTeamsByProjectIds/',
  Problems:'http://localhost:50653/api/Problems/',
  updateRequest:'http://localhost:50653/api/Request/',
  RequestProblems:'http://localhost:50653/api/RequestProblems/',
  GetProblemByEmployeeIdAndRequestId:'http://localhost:50653/api/RequestProblems/GetProblemByEmployeeIdAndRequestId/',
  GetAllDescByRequestID:'http://localhost:50653/api/RequestDescription/GetAllDescriptionsByRequestId/',
  getImageByName:'http://localhost:50653/api/Employees/getImage/',
  GetEmployeeByDepartmentId:'http://localhost:50653/api/Employees/GetEmployeeByDepartmentId/',
  GetAllProjectsByProjectTypeId:'http://localhost:50653/api/Project/GetAllProjectsByProjectTypeId/',
  GetAllRequestByRequestStatus:'http://localhost:50653/api/Request/GetAllRequestByRequestStatus/',
  CountProject:'http://localhost:50653/api/Request/CountProjects/',
  CountInProgressProjects:'http://localhost:50653/api/Request/CountInProgressProjects/',
  CountOpenProjects:'http://localhost:50653/api/Request/CountOpenProjects/',
  CountClosedProjects:'http://localhost:50653/api/Request/CountClosedProjects/',
  GetAllRequestByRequestStatusAndProjectTeamId:'http://localhost:50653/api/Request/GetAllRequestByRequestStatusAndProjectTeamId/',
  Sites:'http://localhost:50653/api/Sites',
  Origins:'http://localhost:50653/api/Origins',
  Suppliers:'http://localhost:50653/api/Suppliers',
  DueDateCategory:'http://localhost:50653/api/DueDateCategory',
  Brand:'http://localhost:50653/api/Brand',
  ProjectSites:'http://localhost:50653/api/ProjectSites',
  GetAllSitesByProjectId:'http://localhost:50653/api/ProjectSites/GetAllSitesByProjectId',
  SiteClients:'http://localhost:50653/api/SiteClients',
  GetAllUnassignedClients:'http://localhost:50653/api/SiteClients/GetAllUnassignedClients',
  GetAllAssignedClients:'http://localhost:50653/api/SiteClients/GetAllAssignedClients',
  GetAllAssignedClientsByProjectId:'http://localhost:50653/api/SiteClients/GetAllAssignedClientsByProjectId',
  GetAllUnassignedClientsforAnotherProjectAndAssignedByThisProjectId:'http://localhost:50653/api/SiteClients/GetAllUnassignedClientsforAnotherProjectAndAssignedByThisProjectId',
  GetProjectSiteByProjectIdAndSiteId:'http://localhost:50653/api/ProjectSites/GetProjectSiteByProjectIdAndSiteId',
  ProjectSiteAsset:'http://localhost:50653/api/ProjectSiteAsset',
  GetAllProjectSiteAssetBySiteId:'http://localhost:50653/api/ProjectSiteAsset/GetAllProjectSiteAssetBySiteId',
  GetAllProjectSiteAssetByProjectId:'http://localhost:50653/api/ProjectSiteAsset/GetAllProjectSiteAssetByProjectId',
  OrganizationClients:'http://localhost:50653/api/OrganizationClients',
  GetAllUnassignedClientsByOrganization:'http://localhost:50653/api/OrganizationClients/GetAllUnassignedClients',
  GetAllAssignedClientsByOrganizationId:'http://localhost:50653/api/OrganizationClients/GetAllAssignedClientsByOrganizationId',
  GetAllUnassignedClientsforAnotherOrganizationAndAssignedByThisOrganizationId:'http://localhost:50653/api/OrganizationClients/GetAllUnassignedClientsforAnotherOrganizationAndAssignedByThisOrganizationId',
  GetAllAssignedClientsDataByOrganizationId:'http://localhost:50653/api/OrganizationClients/GetAllAssignedClientsDataByOrganizationId',
  GetOrganizationProjectsByClientId:'http://localhost:50653/api/OrganizationClients/GetOrganizationProjectsByClientId',
  GetAllRequestByProjectId: 'http://localhost:50653/api/Request/GetAllRequestByProjectId/',
  GetAllAssetsSerialsByAssetId:'http://localhost:50653/api/ProjectSiteAsset/GetAllAssetsSerialsByAssetId',
  GetProjectsByClientId: 'http://localhost:50653/api/project/GetProjectsByClientId/',
  clientCanRequest:'http://localhost:50653/api/project/clientCanRequest/',
  GetAllRequestByProjectSiteAssetId:'http://localhost:50653/api/Request/GetAllRequestByProjectSiteAssetId/',
  GetProjectSiteAssetBySerialNumber:'http://localhost:50653/api/ProjectSiteAsset/GetProjectSiteAssetBySerialNumber',




  
  production: false 

};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
